# Dashboards need to be specified here to be created on TestGrid
# A prow annotation will be invalid if it references a dashboard that doesn't exist
dashboards:
- name: googleoss-gcp-guest
- name: googleoss-compute-image-import
- name: googleoss-test-infra
- name: googleoss-esp-v2-presubmit
- name: googleoss-esp-v2-postsubmit
- name: googleoss-esp-v2-periodic
- name: googleoss-kubeflow-pipelines
- name: googleoss-kubeflow-gcp-blueprints
- name: googleoss-grpc-transcoder
- name: googleoss-http-pattern-matcher
- name: googleoss-kpt-config-sync-multi-repo-1
- name: googleoss-kpt-config-sync-multi-repo-2
- name: googleoss-kpt-config-sync-multi-repo-3
- name: googleoss-kpt-config-sync-multi-repo-4
- name: googleoss-kpt-config-sync-multi-repo-5
- name: googleoss-kpt-config-sync-multi-repo-6
- name: googleoss-kpt-config-sync-multi-repo-7
- name: googleoss-kpt-config-sync-multi-repo-8
- name: googleoss-kpt-config-sync-misc

dashboard_groups:
  - name: googleoss
    dashboard_names:
    - googleoss-gcp-guest
    - googleoss-compute-image-import
    - googleoss-test-infra
    - googleoss-esp-v2-presubmit
    - googleoss-esp-v2-postsubmit
    - googleoss-esp-v2-periodic
    - googleoss-grpc-transcoder
    - googleoss-http-pattern-matcher
  - name: googleoss-kubeflow
    dashboard_names:
    - googleoss-kubeflow-pipelines
    - googleoss-kubeflow-gcp-blueprints
  - name: googleoss-kpt-config-sync
    dashboard_names:
    - googleoss-kpt-config-sync-multi-repo-1
    - googleoss-kpt-config-sync-multi-repo-2
    - googleoss-kpt-config-sync-multi-repo-3
    - googleoss-kpt-config-sync-multi-repo-4
    - googleoss-kpt-config-sync-multi-repo-5
    - googleoss-kpt-config-sync-multi-repo-6
    - googleoss-kpt-config-sync-multi-repo-7
    - googleoss-kpt-config-sync-multi-repo-8
    - googleoss-kpt-config-sync-misc
