presubmits:
  https://kunit-review.googlesource.com/linux:
  - name: kunit-test-presubmit
    branches:
    - kunit/alpha/master
    decorate: true
    always_run: true
    spec:
      volumes:
      - name: shared-mem
        emptyDir: {}
      containers:
      - image: gcr.io/kunit-prow-container-registry/kunit
        securityContext:
          privileged: true
        command:
        - /kunit.sh
        volumeMounts:
        - name: shared-mem
          mountPath: /dev/shm
