# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

tide:
  merge_method:
    chaotoppicks: squash
    GoogleCloudPlatform/guest-agent: squash
    GoogleCloudPlatform/guest-configs: squash
    GoogleCloudPlatform/guest-diskexpand: squash
    GoogleCloudPlatform/guest-logging-go: squash
    GoogleCloudPlatform/guest-oslogin: squash
    GoogleCloudPlatform/guest-test-infra: squash
    GoogleCloudPlatform/osconfig: squash
    GoogleCloudPlatform/artifact-registry-apt-transport: squash
    GoogleCloudPlatform/artifact-registry-yum-plugin: squash
    kubeflow: squash
  merge_commit_template:
    kubeflow:
      title: "{{ .Title }} (#{{ .Number }})"
  target_url: https://oss-prow.knative.dev/tide
  queries:
  - repos:
    - GoogleCloudPlatform/guest-agent
    - GoogleCloudPlatform/guest-configs
    - GoogleCloudPlatform/guest-diskexpand
    - GoogleCloudPlatform/guest-logging-go
    - GoogleCloudPlatform/guest-oslogin
    - GoogleCloudPlatform/guest-test-infra
    - GoogleCloudPlatform/osconfig
    - GoogleCloudPlatform/artifact-registry-apt-transport
    - GoogleCloudPlatform/artifact-registry-yum-plugin
    - GoogleCloudPlatform/oss-test-infra
    - GoogleCloudPlatform/testgrid
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
  - orgs:
    - chaotoppicks
    - kubeflow
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase

plank:
  job_url_prefix_config:
    '*': https://oss-prow.knative.dev/view/
    'chaotoppicks': https://oss-prow-private.knative.dev/view/
    'looker': https://oss-prow-private.knative.dev/view/
  pod_pending_timeout: 15m
  pod_unscheduled_timeout: 1m
  default_decoration_config_entries:
  - config:
      timeout: 7200000000000 # 2h
      grace_period: 15000000000 # 15s
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20210502-ba10239e8c"
        initupload: "gcr.io/k8s-prow/initupload:v20210502-ba10239e8c"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20210502-ba10239e8c"
        sidecar: "gcr.io/k8s-prow/sidecar:v20210502-ba10239e8c"
      gcs_configuration:
        bucket: "oss-prow"
        path_strategy: "explicit"
      gcs_credentials_secret: "service-account" # TODO(fejta): remove https://github.com/GoogleCloudPlatform/oss-test-infra/issues/202
  - cluster: build-looker-private
    config:
      gcs_configuration:
        bucket: "looker-private"
      gcs_credentials_secret: "" # Use workload identity
      default_service_account_name: "prowjob-default-sa" # SA in build cluster
      ssh_key_secrets:
      - looker-ssh-deploy-key

sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 48h
  terminated_pod_ttl: 30m

prowjob_namespace: default
pod_namespace: test-pods
log_level: debug

managed_webhooks:
  # Will accept invitations from org/repo listed under here
  auto_accept_invitation: true
  # Config for orgs and repos that have been onboarded to this Prow instance.
  org_repo_config:
    chaotoppicks: # Temporarily added for experimenting inrepoconfig
      token_created_after: 2021-04-19T00:10:00Z
    google/http_pattern_matcher:
      token_created_after: 2021-03-15T00:10:00Z
    googleforgames/agones:
      token_created_after: 2021-04-22T00:10:00Z
    grpc-ecosystem/grpc-httpjson-transcoding:
      token_created_after: 2021-04-22T00:10:00Z
    GoogleCloudPlatform/artifact-registry-apt-transport:
      token_created_after: 2021-03-04T00:10:00Z
    GoogleCloudPlatform/artifact-registry-yum-plugin:
      token_created_after: 2021-03-04T00:10:00Z
    GoogleCloudPlatform/compute-image-tools:
      token_created_after: 2021-04-22T00:10:00Z
    GoogleCloudPlatform/esp-v2:
      token_created_after: 2021-04-21T00:10:00Z
    GoogleCloudPlatform/guest-agent:
      token_created_after: 2021-04-22T00:10:00Z
    GoogleCloudPlatform/guest-configs:
      token_created_after: 2021-04-22T00:10:00Z
    GoogleCloudPlatform/guest-diskexpand:
      token_created_after: 2021-04-22T00:10:00Z
    GoogleCloudPlatform/guest-logging-go:
      token_created_after: 2021-04-22T00:10:00Z
    GoogleCloudPlatform/guest-oslogin:
      token_created_after: 2021-04-22T00:10:00Z
    GoogleCloudPlatform/guest-test-infra:
      token_created_after: 2021-04-22T00:10:00Z
    GoogleCloudPlatform/k8s-cloud-provider:
      token_created_after: 2021-04-22T00:10:00Z
    GoogleCloudPlatform/osconfig:
      token_created_after: 2021-04-22T00:10:00Z
    GoogleCloudPlatform/oss-test-infra:
      token_created_after: 2021-04-22T00:10:00Z
    GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp:
      token_created_after: 2020-10-13T00:10:00Z
    GoogleCloudPlatform/testgrid:
      token_created_after: 2021-04-21T00:10:00Z
    kubeflow:
      token_created_after: 2020-12-06T00:10:00Z
    looker:
      token_created_after: 2021-04-28T00:10:00Z
#    [org_name]/[repo_name]:
#      token_created_after: 2020-08-18T00:10:00Z

branch-protection:
  orgs:
    kubeflow:
      protect: true
      required_status_checks:
        contexts:
        - cla/google
      exclude:
      - "^revert-" # don't protect revert branches
      - "^dependabot/" # don't protect branches created by dependabot
      - "-patch-" # don't protect branches created by editing on GitHub UI
    chaotoppicks:
      protect: true
      required_status_checks:
        contexts:
        - cla/google
      exclude:
      - "^revert-" # don't protect revert branches
      - "-patch-" # don't protect branches created by editing on GitHub UI

deck:
  spyglass:
    size_limit: 500000000 # 500MB
    gcs_browser_prefix: https://pantheon.corp.google.com/storage/browser/ # TODO(fejta): something publicly accessible
    testgrid_config: gs://k8s-testgrid/config
    testgrid_root: https://testgrid.k8s.io/
    lenses:
      - lens:
          name: metadata
        required_files:
          - started.json|finished.json
        optional_files:
          - podinfo.json
      - lens:
          name: buildlog
        required_files:
          - build-log.txt
      - lens:
          name: junit
        required_files:
          - artifacts/junit.*\.xml
      - lens:
          name: podinfo
        required_files:
          - podinfo.json
  rerun_auth_configs:
    '*':
      github_orgs:
      - GoogleCloudPlatform
  additional_allowed_buckets:
    - compute-image-tools-test
  hidden_repos:
  - chaotoppicks
  - looker

in_repo_config:
  enabled:
    chaotoppicks: true
    looker/helltool: true

  allowed_clusters:
    # TODO(chaodaiG): drop this once
    # https://github.com/kubernetes/test-infra/pull/21993 is deployed in OSS
    # prow
    "*": ["non-exist-cluster-since-global-cluster-is-disabled"]
    "chaotoppicks/great-private-tools": ["build-looker-private"]
    "looker/helltool": ["build-looker-private"]

presets:
# docker-in-docker preset
#
# NOTE: This requires using an entrypoint or base image with the runner.sh
# script. An example can be found at:
#
#   https://github.com/kubernetes/test-infra/blob/master/images/bootstrap/runner.sh
#
# You must ALSO set the following on your PodSpec:
#
#   securityContext:
#     privileged: true
- labels:
    preset-dind-enabled: "true"
  env:
  - name: DOCKER_IN_DOCKER_ENABLED
    value: "true"
  volumes:
  - name: docker-graph
    emptyDir: {}
  volumeMounts:
  - name: docker-graph
    mountPath: /docker-graph
