presubmits:
  GoogleCloudPlatform/blueprints:
  - name: pull-blueprints-validate-prow-yaml
    cluster: build-blueprints
    run_if_changed: ^\.prow(/|\.yaml$)
    decorate: true
    extra_refs:
    - org: GoogleCloudPlatform
      repo: oss-test-infra
      base_ref: master
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/gob-prow/prow-images/checkconfig:v20250919-1b27abd4a
        command:
        - checkconfig
        args:
        - --plugin-config=../../GoogleCloudPlatform/oss-test-infra/prow/oss/plugins.yaml
        - --config-path=../../GoogleCloudPlatform/oss-test-infra/prow/oss/config.yaml
        - --job-config-path=../../GoogleCloudPlatform/oss-test-infra/prow/prowjobs
        - --prow-yaml-repo-name=$(REPO_OWNER)/$(REPO_NAME)
        - --strict
        - --exclude-warning=mismatched-tide
        - --exclude-warning=non-decorated-jobs
        - --warnings=unknown-fields-all
        - --include-default-warnings
