apiVersion: apps/v1
kind: Deployment
metadata:
  name: deck-private
  namespace: default
  labels:
    app: deck-private
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deck-private
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: deck-private
    spec:
      serviceAccountName: deck-private
      terminationGracePeriodSeconds: 30
      containers:
      - name: deck-private
        image: gcr.io/k8s-prow/deck:v20220513-69ff551a87
        ports:
        - name: http
          containerPort: 8080
        args:
        - --config-path=/etc/config/config.yaml
        - --hook-url=http://hook:8888/plugin-help
        - --tide-url=http://tide/
        - --job-config-path=/etc/job-config
        - --redirect-http-to=oss-private.gprow.dev
        - --spyglass=true
        - --tenant-id=looker
        - --rerun-creates-job
        - --oauth-url=/github-login
        - --github-token-path=/etc/github/oauth
        - --github-oauth-config-file=/etc/githuboauth/secret
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --cookie-secret=/etc/cookie/secret
        - --plugin-config=/etc/plugins/plugins.yaml
        env:
        # Use KUBECONFIG envvar rather than --kubeconfig flag in order to provide multiple configs to merge.
        - name: KUBECONFIG
          value: "/etc/kubeconfig/config-20211108:/etc/build-compute-image-import/kubeconfig:/etc/build-bms-oracle-team/kubeconfig:/etc/build-looker-32/kubeconfig:/etc/build-looker-16/kubeconfig:/etc/build-looker-int-test/kubeconfig:/etc/build-elcarro/kubeconfig:/etc/build-looker-private/kubeconfig:/etc/build-kubeflow/kubeconfig"
        volumeMounts:
        - mountPath: /etc/build-compute-image-import
          name: build-compute-image-import
          readOnly: true
        - mountPath: /etc/build-bms-oracle-team
          name: build-bms-oracle-team
          readOnly: true
        - mountPath: /etc/build-looker-32
          name: build-looker-32
          readOnly: true
        - mountPath: /etc/build-looker-16
          name: build-looker-16
          readOnly: true
        - mountPath: /etc/build-looker-int-test
          name: build-looker-int-test
          readOnly: true
        - mountPath: /etc/build-elcarro
          name: build-elcarro
          readOnly: true
        - mountPath: /etc/build-looker-private
          name: build-looker-private
          readOnly: true
        - name: oauth-config
          mountPath: /etc/githuboauth
          readOnly: true
        - name: cookie-secret
          mountPath: /etc/cookie
          readOnly: true
        - name: oauth-token
          mountPath: /etc/github
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: job-config
          mountPath: /etc/job-config
          readOnly: true
        - name: plugins
          mountPath: /etc/plugins
          readOnly: true
        - mountPath: /etc/kubeconfig
          name: kubeconfig
          readOnly: true
        - name: build-kubeflow
          mountPath: /etc/build-kubeflow
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 600
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
        args:
        - --provider=github
        - --github-org=looker
        - --github-team=eng
        - --http-address=0.0.0.0:4180
        - --upstream=http://localhost:8080
        - --cookie-domain=oss-private.gprow.dev
        - --cookie-name=oss-private-gprow-dev-oauth2-proxy
        - --cookie-samesite=none
        - --cookie-expire=23h
        - --email-domain=*
        livenessProbe:
          httpGet:
            path: /ping
            port: 4180
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ping
            port: 4180
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: private-deck-oauth2
              key: clientID
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: private-deck-oauth2
              key: clientSecret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: private-deck-oauth2
              key: cookieSecret
      volumes:
      - name: build-compute-image-import
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-compute-image-import
      - name: build-bms-oracle-team
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-bms-oracle-team
      - name: build-looker-32
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-looker-32
      - name: build-looker-16
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-looker-16
      - name: build-looker-int-test
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-looker-int-test
      - name: build-elcarro
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-elcarro
      - name: build-looker-private
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-looker-private
      - name: oauth-config
        secret:
          secretName: private-deck-oauth2-config
      - name: oauth-token
        secret:
          secretName: oauth-token-2
      - name: cookie-secret
        secret:
          secretName: cookie
      - name: config
        configMap:
          name: config
      - name: job-config
        configMap:
          name: job-config
      - name: plugins
        configMap:
          name: plugins
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: kubeconfig
      - name: build-kubeflow
        secret:
          defaultMode: 420
          secretName: kubeconfig-build-kubeflow
---
apiVersion: v1
kind: Service
metadata:
  name: deck-private
  namespace: default
spec:
  selector:
    app: deck-private
  ports:
  - port: 80
    targetPort: 4180
  type: NodePort
---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: deck-private
  annotations:
    "iam.gke.io/gcp-service-account": "oss-prow-private-deck@oss-prow.iam.gserviceaccount.com"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: deck-private
rules:
- apiGroups:
  - prow.k8s.io
  resources:
  - prowjobs
  verbs:
  - get
  - list
  - watch
  - create
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-pods
  name: deck-private
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: deck-private
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deck-private
subjects:
- kind: ServiceAccount
  name: deck-private
  namespace: default
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-pods
  name: deck-private
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deck-private
subjects:
- kind: ServiceAccount
  name: deck-private
  namespace: default
