presubmits:
  GoogleCloudPlatform/oss-test-infra:

    - name: pull-prow-config-validate
      branches:
        - master
      decorate: true
      always_run: true
      spec:
        containers:
          - image: gcr.io/k8s-prow/checkconfig:v20190924-cb71f84e1
            imagePullPolicy: Always
            command:
              - /checkconfig
            args:
              - --config-path=./prow/config.yaml
              - --job-config-path=./prow/prowjobs

    - name: pull-test-infra-go-test
      branches:
        - master
      decorate: true
      always_run: true
      spec:
        containers:
          - image: golang:1.13
            command:
              - go
              - test
              - ./...

postsubmits:
    GoogleCloudPlatform/oss-test-infra:

    - name: post-test-infra-deploy-prow
      cluster: test-infra-trusted
      run_if_changed: '^prow/cluster/'
      decorate: true
      branches:
      - master
      labels:
          preset-prow-deployer-service-account: "true"
      spec:
          containers:
          - image: gcr.io/k8s-testimages/gcloud-in-go:v20190125-cc5d6ecff3
            command:
            - make
            args:
            - -C
            - prow
            - deploy
            - deploy-build