postsubmits:
  GoogleCloudPlatform/oss-test-infra:
  - name: post-oss-test-infra-deploy-prow
    cluster: test-infra-trusted
    run_if_changed: '^prow/oss/Makefile|^prow/oss/cluster/|^prow/oss/serviceaccounts/|^prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml'
    decorate: true
    branches:
    - master
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: prow-deploy
      testgrid-alert-email: prow-alert-pioneer@google.com
      testgrid-num-failures-to-alert: '2'
    spec:
      serviceAccountName: prow-deployer
      containers:
      - image: gcr.io/k8s-staging-test-infra/gcloud-in-go:v20230111-cd1b3caf9c
        command:
        - make
        args:
        - -C
        - prow/oss
        - deploy
        - deploy-build
        - deploy-monitoring
  - name: post-oss-test-infra-create-testgrid-config
    cluster: test-infra-trusted
    branches:
    - ^master$
    max_concurrency: 1
    labels:
      preset-bazel-scratch-dir: "true"
    run_if_changed: '^(prow/prowjobs/.*\.yaml)|(testgrid/config\.yaml)$'
    decorate: true
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: testgrid-gcs-upload
      testgrid-alert-email: prow-alert-pioneer@google.com
      testgrid-num-failures-to-alert: '1'
    spec:
      serviceAccountName: testgrid-config-updater
      containers:
      - image: gcr.io/k8s-staging-test-infra/configurator:v20240914-93a93a3da9
        command:
        - configurator
        args:
        - --yaml=testgrid/config.yaml
        - --default=testgrid/default.yaml
        - --prow-config=prow/oss/config.yaml
        - --prow-job-config=prow/prowjobs
        - --output=gs://oss-prow-own-testgrid/config
        - --prowjob-url-prefix=https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/prowjobs/
        - --update-description
        - --oneshot
        resources:
          requests:
            memory: "1Gi"
  - name: post-test-infra-gencred-refresh-kubeconfig
    cluster: test-infra-trusted
    run_if_changed: '^prow/oss/gencred-config/'
    decorate: true
    branches:
    - ^master$
    spec:
      serviceAccountName: gencred-refresher
      containers:
      - name: gencred
        image: gcr.io/k8s-staging-test-infra/gencred:v20240914-93a93a3da9
        command:
        - gencred
        args:
        - --config=./prow/oss/gencred-config/gencred-config.yaml
    annotations:
      testgrid-num-failures-to-alert: '1'
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: postsubmit-gencred-refresh-kubeconfig
      testgrid-alert-email: prow-alert-pioneer@google.com
      description: Runs gencred to refresh generated kubeconfigs.

periodics:
- cron: "30 * * * 1-5"  # Bump don't label `skip-review`. Run at :30 past every hour Mon-Fri
  name: ci-oss-test-infra-autobump-prow
  cluster: test-infra-trusted
  decorate: true
  extra_refs:
  - org: GoogleCloudPlatform
    repo: oss-test-infra
    base_ref: master
  annotations:
    testgrid-dashboards: googleoss-test-infra
    testgrid-tab-name: autobump-prow
    testgrid-alert-email: prow-alert-pioneer@google.com
    testgrid-num-failures-to-alert: '3'
  spec:
    containers:
    - image: us-central1-docker.pkg.dev/gob-prow/prow-images/generic-autobumper:v20250509-70d51bf43
      command:
      - generic-autobumper
      args:
      - --config=prow/oss/oss-prow-autobump-config.yaml
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
      - name: ssh
        mountPath: /root/.ssh
    volumes:
    - name: github
      secret:
        secretName: oauth-token-2
    - name: ssh
      secret:
        secretName: google-oss-robot-ssh-keys
        defaultMode: 0400
- cron: "30 * * * 1-5"  # Bump don't label `skip-review`. Run at :30 past every hour Mon-Fri
  name: ci-oss-test-infra-autobump-misc
  cluster: test-infra-trusted
  decorate: true
  extra_refs:
  - org: GoogleCloudPlatform
    repo: oss-test-infra
    base_ref: master
  annotations:
    testgrid-dashboards: googleoss-test-infra
    testgrid-tab-name: autobump-misc
    testgrid-alert-email: prow-alert-pioneer@google.com
    testgrid-num-failures-to-alert: '3'
  spec:
    containers:
    - image: us-central1-docker.pkg.dev/gob-prow/prow-images/generic-autobumper:v20250509-70d51bf43
      command:
      - generic-autobumper
      args:
      - --config=prow/oss/misc-images-autobump-config.yaml
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
      - name: ssh
        mountPath: /root/.ssh
    volumes:
    - name: github
      secret:
        secretName: oauth-token-2
    - name: ssh
      secret:
        secretName: google-oss-robot-ssh-keys
        defaultMode: 0400
# ci-oss-test-infra-heartbeat is used for prometheus, alert(s) will be sent
# if this job hadn't been succeeded for some time
- cron: "*/3 * * * *" # Every 3 minutes
  name: ci-oss-test-infra-heartbeat
  decorate: true
  cluster: test-infra-trusted
  extra_refs:
  - org: GoogleCloudPlatform
    repo: oss-test-infra
    base_ref: master
  annotations:
    testgrid-dashboards: googleoss-test-infra
    testgrid-tab-name: oss-prow-heartbeat
  spec:
    containers:
    - image: gcr.io/k8s-testimages/gcloud-bazel:v20200520-v0.4-30-g9d6313a
      command:
      - "echo"
      args:
      - "Everything is fine!"
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
- cron: "17 */6 * * *"  # Every 6 hours at 17 minutes past the hour
  name: ci-test-infra-gencred-refresh-kubeconfig
  cluster: test-infra-trusted
  decorate: true
  extra_refs:
  - org: GoogleCloudPlatform
    repo: oss-test-infra
    base_ref: master
  spec:
    serviceAccountName: gencred-refresher
    containers:
    - name: gencred
      image: gcr.io/k8s-staging-test-infra/gencred:v20240914-93a93a3da9
      command:
      - gencred
      args:
      - --config=./prow/oss/gencred-config/gencred-config.yaml
  annotations:
    testgrid-num-failures-to-alert: '3'
    testgrid-alert-stale-results-hours: '12'
    testgrid-dashboards: googleoss-test-infra
    testgrid-tab-name: ci-gencred-refresh-kubeconfig
    testgrid-alert-email: prow-alert-pioneer@google.com
    description: Runs gencred to refresh generated kubeconfigs.
