presubmits:
  GoogleCloudPlatform/oss-test-infra:

    - name: pull-prow-config-validate
      branches:
        - master
      decorate: true
      cluster: build
      always_run: true
      spec:
        containers:
          - image: gcr.io/k8s-prow/checkconfig:v20190924-cb71f84e1
            imagePullPolicy: Always
            command:
              - /checkconfig
            args:
              - --config-path=./prow/config.yaml
              - --job-config-path=./prow/prowjobs

    - name: pull-test-infra-go-test
      branches:
        - master
      decorate: true
      cluster: build
      always_run: true
      spec:
        containers:
          - image: golang:1.13
            command:
              - go
              - test
              - ./...
