presubmits:
  GoogleCloudPlatform/oss-test-infra:
  - name: pull-prow-config-validate
    branches:
      - master
    decorate: true
    always_run: true
    spec:
      containers:
        - image: gcr.io/k8s-prow/checkconfig:v20210105-c50d055243
          imagePullPolicy: Always
          command:
            - /checkconfig
          args:
            - --config-path=./prow/oss/config.yaml
            - --job-config-path=./prow/prowjobs
            - --plugin-config=prow/oss/plugins.yaml
            - --strict
            # This warning can forbid valid (and convenient) config. Exclude it.
            # Details: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/131#discussion_r334208082
            - --exclude-warning=mismatched-tide
            - --exclude-warning=non-decorated-jobs
  - name: pull-lint-validator
    branches:
      - master
    decorate: true
    always_run: true
    spec:
      containers:
        - image: cytopia/yamllint
          imagePullPolicy: Always
          command:
            - yamllint
            - -c
            - common/config/.yamllint.conf
            - .
  - name: pull-test-infra-go-test
    branches:
      - master
    decorate: true
    always_run: true
    spec:
      containers:
        - image: golang:1.13
          command:
            - go
            - test
            - ./...
  - name: pull-oss-test-infra-check-testgrid-config
    run_if_changed: '^(prow/prowjobs/.*\.yaml)|(testgrid/config\.yaml)$'
    decorate: true
    branches:
    - master
    annotations:
      testgrid-create-test-group: "false"
    spec:
      containers:
      - image: gcr.io/k8s-prow/transfigure
        command:
        - /transfigure.sh
        args:
        - test
        - prow/oss/config.yaml
        - prow/prowjobs
        - testgrid/config.yaml
        - GoogleCloudPlatform
  - name: pull-knative-prow-config-validate
    run_if_changed: '^prow/knative/(config|plugins)\.yaml$'
    branches:
      - master
    decorate: true
    extra_refs:
    - org: knative
      repo: test-infra
      base_ref: master
    spec:
      containers:
        - image: gcr.io/k8s-prow/checkconfig:v20210105-c50d055243
          imagePullPolicy: Always
          command:
            - /checkconfig
          args:
            - --config-path=./prow/knative/config.yaml
            - --job-config-path=../../knative/test-infra/config/prod/prow/jobs
            - --plugin-config=prow/knative/plugins.yaml
            - --strict
            # This warning can forbid valid (and convenient) config. Exclude it.
            # Details: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/131#discussion_r334208082
            - --exclude-warning=mismatched-tide
            - --exclude-warning=non-decorated-jobs
            - --exclude-warning=long-job-names

postsubmits:
  GoogleCloudPlatform/oss-test-infra:
  - name: post-oss-test-infra-deploy-prow
    cluster: test-infra-trusted
    run_if_changed: '^prow/oss/cluster/|^prow/oss/serviceaccounts/|^prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml'
    decorate: true
    branches:
    - master
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: prow-deploy
      testgrid-alert-email: k8s-infra-oncall@google.com
      testgrid-num-failures-to-alert: '2'
    spec:
      serviceAccountName: prow-deployer
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20200109-87b811d
        command:
        - make
        args:
        - -C
        - prow/oss
        - deploy
        - deploy-build
        - deploy-monitoring
  - name: post-oss-test-infra-deploy-knative-prow
    cluster: test-infra-trusted
    run_if_changed: '^prow/knative/cluster/|^prow/oss/serviceaccounts/'
    decorate: true
    branches:
    - master
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: knative-prow-deploy
      testgrid-alert-email: k8s-infra-oncall@google.com
      testgrid-num-failures-to-alert: '2'
    spec:
      serviceAccountName: prow-deployer
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20200109-87b811d
        command:
        - make
        args:
        - -C
        - prow/knative
        - deploy
        - deploy-build
        - deploy-monitoring
  - name: post-oss-test-infra-upload-testgrid-config
    cluster: test-infra-trusted
    run_if_changed: '^(prow/prowjobs/.*\.yaml)|(testgrid/config\.yaml)$'
    decorate: true
    branches:
    - master
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: testgrid-upload
      testgrid-alert-email: k8s-infra-oncall@google.com
      testgrid-num-failures-to-alert: '2'
    spec:
      containers:
      - image: gcr.io/k8s-prow/transfigure
        command:
        - /transfigure.sh
        args:
        - /etc/github-token/oauth
        - prow/oss/config.yaml
        - prow/prowjobs
        - testgrid/config.yaml
        - GoogleCloudPlatform
        volumeMounts:
        - name: github
          mountPath: /etc/github-token
          readOnly: true
      volumes:
      - name: github
        secret:
          secretName: oauth-token
  - name: post-oss-test-infra-reconcile-hmacs
    cluster: test-infra-trusted
    run_if_changed: 'prow/oss/config.yaml'
    decorate: true
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: hmacs-reconciliation
      testgrid-alert-email: k8s-infra-oncall@google.com
      testgrid-num-failures-to-alert: '1'
    branches:
    - master
    spec:
      containers:
      - image: gcr.io/k8s-prow/hmac:v20210105-c50d055243
        command:
        - /hmac
        args:
        - --config-path=prow/oss/config.yaml
        - --hook-url=https://oss-prow.knative.dev/hook
        - --hmac-token-secret-name=hmac-token
        - --hmac-token-key=hmac
        - --kubeconfig=/etc/kubeconfig/config
        - --kubeconfig-context=prow-services
        - --github-token-path=/etc/github/oauth
        - --github-endpoint=http://ghproxy.default.svc.cluster.local
        - --github-endpoint=https://api.github.com
        - --dry-run=false
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubeconfig
          readOnly: true
        - name: oauth
          mountPath: /etc/github
          readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: kubeconfig-prow-services
      - name: oauth
        secret:
          defaultMode: 420
          secretName: oauth-token

  GoogleCloudPlatform/testgrid:
  - name: push-testgrid-images
    cluster: test-infra-trusted
    branches:
    - ^master$
    decorate: true
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-alert-email: slchase@google.com
      testgrid-tab-name: testgrid-push
    spec:
      serviceAccountName: testgrid-pusher
      containers:
      - image: gcr.io/k8s-testimages/bazelbuild:v20200609-e7bfd25-test-infra
        command:
        - ./images/push.sh
  - name: post-testgrid-deploy-prod
    cluster: test-infra-trusted
    branches:
    - ^master$
    run_if_changed: '^cluster/prod'
    decorate: true
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: testgrid-deploy-prod
    spec:
      serviceAccountName: testgrid-deployer
      containers:
      - image: gcr.io/k8s-testimages/gcloud-bazel:v20200520-v0.4-30-g9d6313a
        command:
        - ./cluster/deploy.sh
        args:
        - --confirm
        - //cluster/prod:prod.apply
  - name: post-testgrid-deploy-canary
    cluster: test-infra-trusted
    branches:
    - ^master$
    run_if_changed: '^cluster/canary'
    decorate: true
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: testgrid-deploy-canary
    spec:
      serviceAccountName: testgrid-deployer
      containers:
      - image: gcr.io/k8s-testimages/gcloud-bazel:v20200520-v0.4-30-g9d6313a
        command:
        - ./cluster/deploy.sh
        args:
        - --confirm
        - //cluster/canary:canary.apply
  - name: testgrid-prod-autobump
    cluster: test-infra-trusted
    branches:
    - ^master$
    run_if_changed: '^cluster/canary'
    decorate: true
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: autobump-testgrid-prod
      testgrid-alert-email: k8s-infra-oncall@google.com
      testgrid-num-failures-to-alert: '3'
    spec:
      containers:
      - image: gcr.io/k8s-testimages/generic_autobump:v20210106-34a4396
        command:
        - /generic_autobump
        args:
        - --config=cluster/testgrid-prod-autobump-config.yaml
        volumeMounts:
        - name: github
          mountPath: /etc/github-token
          readOnly: true
      volumes:
      - name: github
        secret:
          secretName: oauth-token

periodics:
- cron: "05 15-23 * * 1-5"  # Run at 7:05-15:05 PST (15:05 UTC) Mon-Fri
  name: ci-oss-test-infra-autobump-prow
  cluster: test-infra-trusted
  decorate: true
  extra_refs:
  - org: GoogleCloudPlatform
    repo: oss-test-infra
    base_ref: master
  annotations:
    testgrid-dashboards: googleoss-test-infra
    testgrid-tab-name: autobump-prow
    testgrid-alert-email: k8s-infra-oncall@google.com
    testgrid-num-failures-to-alert: '3'
  spec:
    containers:
    - image: gcr.io/k8s-prow/autobump:v20210105-c50d055243
      command:
      - /autobump.sh
      args:
      - /etc/github-token/oauth
      - "Google OSS Prow Robot"
      - google-oss-robot@google.com
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
      env:
      - name: GH_ORG
        value: GoogleCloudPlatform
      - name: GH_REPO
        value: oss-test-infra
      - name: PROW_CONTROLLER_MANAGER_FILE
        value: prow/oss/cluster/prow-controller-manager.yaml
      - name: COMPONENT_FILE_DIR
        value: prow/oss/cluster
      - name: CONFIG_PATH
        value: prow/oss/config.yaml
      - name: JOB_CONFIG_PATH
        value: prow/prowjobs
      - name: PROW_INSTANCE_NAME
        value: oss-prow
    volumes:
    - name: github
      secret:
        secretName: oauth-token
- cron: "05 15-23 * * 1-5"  # Run at 7:05-15:05 PST (15:05 UTC) Mon-Fri
  name: testgrid-canary-autobump
  cluster: test-infra-trusted
  decorate: true
  extra_refs:
  - org: GoogleCloudPlatform
    repo: testgrid
    base_ref: master
  annotations:
    testgrid-dashboards: googleoss-test-infra
    testgrid-tab-name: autobump-testgrid-canary
    testgrid-alert-email: k8s-infra-oncall@google.com
    testgrid-num-failures-to-alert: '3'
  spec:
    containers:
    - image: gcr.io/k8s-testimages/generic_autobump:v20210106-34a4396
      command:
      - /generic_autobump
      args:
      - --config=cluster/testgrid-canary-autobump-config.yaml
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
    volumes:
    - name: github
      secret:
        secretName: oauth-token
- cron: "15 15-23 * * 1-5"  # Run at 7:15-15:15 PST (15:15 UTC) Mon-Fri
  name: ci-oss-test-infra-autobump-knative-prow
  cluster: test-infra-trusted
  decorate: true
  extra_refs:
  - org: GoogleCloudPlatform
    repo: oss-test-infra
    base_ref: master
  annotations:
    testgrid-dashboards: googleoss-test-infra
    testgrid-tab-name: autobump-knative-prow
    testgrid-alert-email: k8s-infra-oncall@google.com
    testgrid-num-failures-to-alert: '3'
  spec:
    containers:
    - image: gcr.io/k8s-prow/autobump:v20210105-c50d055243
      command:
      - /autobump.sh
      args:
      - /etc/github-token/oauth
      - "Google OSS Prow Robot"
      - google-oss-robot@google.com
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
      env:
      - name: GH_ORG
        value: GoogleCloudPlatform
      - name: GH_REPO
        value: oss-test-infra
      - name: PROW_CONTROLLER_MANAGER_FILE
        value: prow/knative/cluster/400-prow-controller-manager.yaml
      - name: COMPONENT_FILE_DIR
        value: prow/knative/cluster
      - name: CONFIG_PATH
        value: prow/knative/config.yaml
      - name: PROW_INSTANCE_NAME
        value: knative-prow
    volumes:
    - name: github
      secret:
        secretName: oauth-token
# ci-oss-test-infra-heartbeat is used for prometheus, alert(s) will be sent
# if this job hadn't been succeeded for some time
- cron: "*/3 * * * *" # Every 3 minutes
  name: ci-oss-test-infra-heartbeat
  decorate: true
  cluster: test-infra-trusted
  extra_refs:
  - org: GoogleCloudPlatform
    repo: oss-test-infra
    base_ref: master
  annotations:
    testgrid-dashboards: googleoss-test-infra
    testgrid-tab-name: oss-prow-heartbeat
  spec:
    containers:
    - image: gcr.io/k8s-testimages/gcloud-bazel:v20200520-v0.4-30-g9d6313a
      command:
      - "echo"
      args:
      - "Everything is fine!"
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
