presubmits:
  GoogleCloudPlatform/oss-test-infra:
  - name: pull-prow-config-validate
    branches:
      - master
    decorate: true
    always_run: true
    spec:
      containers:
        - image: gcr.io/k8s-prow/checkconfig:v20210714-62f15287bd
          imagePullPolicy: Always
          command:
            - /checkconfig
          args:
            - --config-path=./prow/oss/config.yaml
            - --job-config-path=./prow/prowjobs
            - --plugin-config=prow/oss/plugins.yaml
            - --strict
            # This warning can forbid valid (and convenient) config. Exclude it.
            # Details: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/131#discussion_r334208082
            - --exclude-warning=mismatched-tide
            - --exclude-warning=non-decorated-jobs
  - name: pull-lint-validator
    branches:
      - master
    decorate: true
    always_run: true
    spec:
      containers:
        - image: cytopia/yamllint
          imagePullPolicy: Always
          command:
            - yamllint
            - -c
            - common/config/.yamllint.conf
            - .
  - name: pull-test-infra-go-test
    branches:
      - master
    decorate: true
    always_run: true
    spec:
      containers:
        - image: golang:1.15
          command:
            - go
            - test
            - ./...
  - name: pull-oss-test-infra-check-create-testgrid-config
    branches:
    - ^master$
    max_concurrency: 1
    run_if_changed: '^(prow/prowjobs/.*\.yaml)|(testgrid/config\.yaml)$'
    decorate: true
    annotations:
      testgrid-create-test-group: "false"
    spec:
      containers:
      - image: gcr.io/k8s-prow/configurator:v20210714-62f15287bd
        command:
        - /app/testgrid/cmd/configurator/app.binary
        args:
        - --yaml=testgrid/config.yaml
        - --default=testgrid/default.yaml
        - --prow-config=prow/oss/config.yaml
        - --prow-job-config=prow/prowjobs
        - --prowjob-url-prefix=https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/prowjobs/
        - --update-description
        - --validate-config-file
        - --oneshot
        resources:
          requests:
            memory: "1Gi"
  - name: pull-knative-prow-config-validate
    run_if_changed: '^prow/knative/(config|plugins)\.yaml$'
    branches:
    - master
    decorate: true
    extra_refs:
    - org: knative
      repo: test-infra
      base_ref: main
    spec:
      containers:
        - image: gcr.io/k8s-prow/checkconfig:v20210714-62f15287bd
          imagePullPolicy: Always
          command:
            - /checkconfig
          args:
            - --config-path=./prow/knative/config.yaml
            - --job-config-path=../../knative/test-infra/config/prod/prow/jobs
            - --plugin-config=prow/knative/plugins.yaml
            - --strict
            # This warning can forbid valid (and convenient) config. Exclude it.
            # Details: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/131#discussion_r334208082
            - --exclude-warning=mismatched-tide
            - --exclude-warning=non-decorated-jobs
            - --exclude-warning=long-job-names
            # TODO: Re-enable these once we're done experimenting with CODEOWNERS in net-contour.
            - --exclude-warning=mismatched-tide-lenient

postsubmits:
  GoogleCloudPlatform/oss-test-infra:
  - name: post-oss-test-infra-deploy-prow
    cluster: test-infra-trusted
    run_if_changed: '^prow/oss/cluster/|^prow/oss/serviceaccounts/|^prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml'
    decorate: true
    branches:
    - master
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: prow-deploy
      testgrid-alert-email: k8s-infra-oncall@google.com
      testgrid-num-failures-to-alert: '2'
    spec:
      serviceAccountName: prow-deployer
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20200824-5d057db
        command:
        - make
        args:
        - -C
        - prow/oss
        - deploy
        - deploy-build
        - deploy-monitoring
  - name: post-oss-test-infra-deploy-knative-prow
    cluster: test-infra-trusted
    run_if_changed: '^prow/knative/cluster/|^prow/oss/serviceaccounts/'
    decorate: true
    branches:
    - master
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: knative-prow-deploy
      testgrid-alert-email: k8s-infra-oncall@google.com
      testgrid-num-failures-to-alert: '2'
    reporter_config:
      slack:
        host: "knative" # Must match additional-slack-token-files in crier deployment
        channel: "test"
        job_states_to_report:
        - success
        - failure
        - aborted
        - error
        report_template: 'Deploying prow: {{.Status.State}}. <{{.Spec.Refs.BaseLink}}|Commit {{.Spec.Refs.BaseSHA}}> <{{.Status.URL}}|View logs> <https://testgrid.k8s.io/googleoss-test-infra#knative-prow-deploy|Job history on Testgrid>'
    spec:
      serviceAccountName: prow-deployer
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20200824-5d057db
        command:
        - make
        args:
        - -C
        - prow/knative
        - deploy
        - deploy-build
        - deploy-monitoring
  - name: post-oss-test-infra-create-testgrid-config
    cluster: test-infra-trusted
    branches:
    - ^master$
    max_concurrency: 1
    labels:
      preset-bazel-scratch-dir: "true"
    run_if_changed: '^(prow/prowjobs/.*\.yaml)|(testgrid/config\.yaml)$'
    decorate: true
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: testgrid-gcs-upload
      testgrid-alert-email: k8s-infra-oncall@google.com
      testgrid-num-failures-to-alert: '1'
    spec:
      serviceAccountName: testgrid-config-updater
      containers:
      - image: gcr.io/k8s-prow/configurator:v20210714-62f15287bd
        command:
        - /app/testgrid/cmd/configurator/app.binary
        args:
        - --yaml=testgrid/config.yaml
        - --default=testgrid/default.yaml
        - --prow-config=prow/oss/config.yaml
        - --prow-job-config=prow/prowjobs
        - --output=gs://oss-prow-own-testgrid/config
        - --prowjob-url-prefix=https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/prowjobs/
        - --update-description
        - --oneshot
        resources:
          requests:
            memory: "1Gi"
  - name: post-oss-test-infra-reconcile-hmacs
    cluster: test-infra-trusted
    run_if_changed: 'prow/oss/config.yaml'
    decorate: true
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: hmacs-reconciliation
      testgrid-alert-email: k8s-infra-oncall@google.com
      testgrid-num-failures-to-alert: '1'
    branches:
    - master
    spec:
      containers:
      - image: gcr.io/k8s-prow/hmac:v20210714-62f15287bd
        command:
        - /hmac
        args:
        - --config-path=prow/oss/config.yaml
        - --hook-url=https://oss-prow.knative.dev/hook
        - --hmac-token-secret-name=hmac-token
        - --hmac-token-key=hmac
        - --kubeconfig=/etc/kubeconfig/config
        - --kubeconfig-context=prow-services
        - --github-token-path=/etc/github/oauth
        - --github-endpoint=http://ghproxy.default.svc.cluster.local
        - --github-endpoint=https://api.github.com
        - --dry-run=false
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubeconfig
          readOnly: true
        - name: oauth
          mountPath: /etc/github
          readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: kubeconfig-prow-services
      - name: oauth
        secret:
          defaultMode: 420
          secretName: oauth-token

  GoogleCloudPlatform/testgrid:
  - name: push-testgrid-images
    cluster: test-infra-trusted
    branches:
    - ^master$
    run_if_changed: '^([^c]|c[^l]|cl[^u]|clu[^s]|clus[^t]|clust[^e]|cluste[^r]).*$' # Anything outside cluster
    decorate: true
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-alert-email: slchase@google.com
      testgrid-tab-name: testgrid-push
    spec:
      serviceAccountName: testgrid-pusher
      containers:
      - image: gcr.io/k8s-testimages/bazelbuild:v20200609-e7bfd25-test-infra
        command:
        - ./images/push.sh
  - name: post-testgrid-deploy-prod
    cluster: test-infra-trusted
    branches:
    - ^master$
    run_if_changed: '^cluster/prod'
    decorate: true
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: testgrid-deploy-prod
    spec:
      serviceAccountName: testgrid-deployer
      containers:
      - image: gcr.io/k8s-testimages/gcloud-bazel:v20200520-v0.4-30-g9d6313a
        command:
        - ./cluster/deploy.sh
        args:
        - --confirm
        - //cluster/prod:prod.apply
  - name: post-testgrid-deploy-canary
    cluster: test-infra-trusted
    branches:
    - ^master$
    run_if_changed: '^cluster/canary'
    decorate: true
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: testgrid-deploy-canary
    spec:
      serviceAccountName: testgrid-deployer
      containers:
      - image: gcr.io/k8s-testimages/gcloud-bazel:v20200520-v0.4-30-g9d6313a
        command:
        - ./cluster/deploy.sh
        args:
        - --confirm
        - //cluster/canary:canary.apply
  - name: testgrid-prod-autobump
    cluster: test-infra-trusted
    branches:
    - ^master$
    run_if_changed: '^cluster/canary'
    decorate: true
    annotations:
      testgrid-dashboards: googleoss-test-infra
      testgrid-tab-name: autobump-testgrid-prod
      testgrid-alert-email: k8s-infra-oncall@google.com
      testgrid-num-failures-to-alert: '3'
    spec:
      containers:
      - image: gcr.io/k8s-prow/generic-autobumper:v20210714-62f15287bd
        command:
        - /app/prow/cmd/generic-autobumper/app.binary
        args:
        - --config=cluster/testgrid-prod-autobump-config.yaml
        volumeMounts:
        - name: github
          mountPath: /etc/github-token
          readOnly: true
        - name: ssh
          mountPath: /root/.ssh
      volumes:
      - name: github
        secret:
          secretName: oauth-token
      - name: ssh
        secret:
          secretName: google-oss-robot-ssh-keys
          defaultMode: 0400

periodics:
- cron: "30 * * * 1-5"  # Bump don't label `skip-review`. Run at :30 past every hour Mon-Fri
  name: ci-oss-test-infra-autobump-prow
  cluster: test-infra-trusted
  decorate: true
  extra_refs:
  - org: GoogleCloudPlatform
    repo: oss-test-infra
    base_ref: master
  annotations:
    testgrid-dashboards: googleoss-test-infra
    testgrid-tab-name: autobump-prow
    testgrid-alert-email: k8s-infra-oncall@google.com
    testgrid-num-failures-to-alert: '3'
  spec:
    containers:
    - image: gcr.io/k8s-prow/generic-autobumper:v20210714-62f15287bd
      command:
      - /app/prow/cmd/generic-autobumper/app.binary
      args:
      - --config=prow/oss/oss-autobump-config.yaml
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
      - name: ssh
        mountPath: /root/.ssh
    volumes:
    - name: github
      secret:
        secretName: oauth-token
    - name: ssh
      secret:
        secretName: google-oss-robot-ssh-keys
        defaultMode: 0400
- cron: "01 18 * * 1-5"  # Bump with label `skip-review`. Run at 11:01 PST (18:01 UTC) Mon-Fri
  name: ci-oss-test-infra-autobump-prow-for-auto-deploy
  cluster: test-infra-trusted
  decorate: true
  extra_refs:
  - org: GoogleCloudPlatform
    repo: oss-test-infra
    base_ref: master
  annotations:
    testgrid-dashboards: googleoss-test-infra
    testgrid-tab-name: autobump-prow-for-auto-deploy
    testgrid-alert-email: k8s-infra-oncall@google.com
    testgrid-num-failures-to-alert: '1'
  spec:
    containers:
    - image: gcr.io/k8s-prow/generic-autobumper:v20210714-62f15287bd
      command:
      - /app/prow/cmd/generic-autobumper/app.binary
      args:
      - --config=prow/oss/oss-autobump-config.yaml
      - --labels-override=skip-review # This label is used by tide for identifying trusted PR
      - --skip-if-no-oncall # Only apply `skip-review` label when oncall is active
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
      - name: ssh
        mountPath: /root/.ssh
    volumes:
    - name: github
      secret:
        secretName: oauth-token
    - name: ssh
      secret:
        secretName: google-oss-robot-ssh-keys
        defaultMode: 0400
- cron: "05 15-23 * * 1-5"  # Run at 7:05-15:05 PST (15:05 UTC) Mon-Fri
  name: testgrid-canary-autobump
  cluster: test-infra-trusted
  decorate: true
  extra_refs:
  - org: GoogleCloudPlatform
    repo: testgrid
    base_ref: master
  annotations:
    testgrid-dashboards: googleoss-test-infra
    testgrid-tab-name: autobump-testgrid-canary
    testgrid-alert-email: k8s-infra-oncall@google.com
    testgrid-num-failures-to-alert: '3'
  spec:
    containers:
    - image: gcr.io/k8s-prow/generic-autobumper:v20210714-62f15287bd
      command:
      - /app/prow/cmd/generic-autobumper/app.binary
      args:
      - --config=cluster/testgrid-canary-autobump-config.yaml
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
      - name: ssh
        mountPath: /root/.ssh
    volumes:
    - name: github
      secret:
        secretName: oauth-token
    - name: ssh
      secret:
        secretName: google-oss-robot-ssh-keys
        defaultMode: 0400
- cron: "15 15-23 * * 1-5"  # Run at 7:15-15:15 PST (15:15 UTC) Mon-Fri
  name: ci-oss-test-infra-autobump-knative-prow
  cluster: test-infra-trusted
  decorate: true
  extra_refs:
  - org: GoogleCloudPlatform
    repo: oss-test-infra
    base_ref: master
  annotations:
    testgrid-dashboards: googleoss-test-infra
    testgrid-tab-name: autobump-knative-prow
    testgrid-alert-email: k8s-infra-oncall@google.com
    testgrid-num-failures-to-alert: '3'
  spec:
    containers:
    - image: gcr.io/k8s-prow/generic-autobumper:v20210714-62f15287bd
      command:
      - /app/prow/cmd/generic-autobumper/app.binary
      args:
      - --config=prow/knative/knative-autobump-config.yaml
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
      - name: ssh
        mountPath: /root/.ssh
    volumes:
    - name: github
      secret:
        secretName: oauth-token
    - name: ssh
      secret:
        secretName: google-oss-robot-ssh-keys
        defaultMode: 0400
- cron: "30 19 * * 1-5"  # Bump with label `skip-review`. Run at 12:30PM PST (19:30 UTC) Mon-Fri
  name: ci-oss-test-infra-autobump-knative-prow-for-auto-deploy
  cluster: test-infra-trusted
  decorate: true
  extra_refs:
  - org: GoogleCloudPlatform
    repo: oss-test-infra
    base_ref: master
  annotations:
    testgrid-dashboards: googleoss-test-infra
    testgrid-tab-name: autobump-knative-prow-for-auto-deploy
    testgrid-alert-email: k8s-infra-oncall@google.com
    testgrid-num-failures-to-alert: '1'
  spec:
    containers:
    - image: gcr.io/k8s-prow/generic-autobumper:v20210714-62f15287bd
      command:
      - /app/prow/cmd/generic-autobumper/app.binary
      args:
      - --config=prow/knative/knative-autobump-config.yaml
      - --labels-override=skip-review # This label is used by tide for identifying trusted PR
      - --skip-if-no-oncall # Only apply `skip-review` label when oncall is active
      volumeMounts:
      - name: github
        mountPath: /etc/github-token
        readOnly: true
      - name: ssh
        mountPath: /root/.ssh
    volumes:
    - name: github
      secret:
        secretName: oauth-token
    - name: ssh
      secret:
        secretName: google-oss-robot-ssh-keys
        defaultMode: 0400
# ci-oss-test-infra-heartbeat is used for prometheus, alert(s) will be sent
# if this job hadn't been succeeded for some time
- cron: "*/3 * * * *" # Every 3 minutes
  name: ci-oss-test-infra-heartbeat
  decorate: true
  cluster: test-infra-trusted
  extra_refs:
  - org: GoogleCloudPlatform
    repo: oss-test-infra
    base_ref: master
  annotations:
    testgrid-dashboards: googleoss-test-infra
    testgrid-tab-name: oss-prow-heartbeat
  spec:
    containers:
    - image: gcr.io/k8s-testimages/gcloud-bazel:v20200520-v0.4-30-g9d6313a
      command:
      - "echo"
      args:
      - "Everything is fine!"
      resources:
        requests:
          cpu: 100m
          memory: 1Gi
